spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/ask_watson?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    # url: jdbc:log4jdbc:mysql://ask-watson.crpktyzigrzp.ap-northeast-2.rds.amazonaws.com:3306/ask_watson?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: apebble
    password: 1pebbla1
    # username : admin
    # password : askwatson


  jpa:
    hibernate:
      ddl-auto: none
      show-ddl: true
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
