spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/ask_watson?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: apebble
    password: pebble1

  jpa:
    hibernate:
      ddl-auto: create-drop
      show-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
